"""
Module 3: Data-Wiki Generator

Automatically generates Markdown data dictionaries for any dataset.
Uses pandas for statistics and Groq LLM for human-readable descriptions.

Knowledge Proved: Scaling technical capabilities and supporting team productivity.
"""

import json
import os
from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime

import pandas as pd
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_groq import ChatGroq

from agents.prompts.wiki_prompts import (
    WIKI_COLUMN_PROMPT,
    WIKI_SUMMARY_PROMPT,
    WIKI_SYSTEM_PROMPT,
)


@dataclass
class ColumnProfile:
    """Profile of a single column in a dataset."""
    name: str
    dtype: str
    description: str = ""
    null_count: int = 0
    null_rate: float = 0.0
    unique_count: int = 0
    sample_values: list = field(default_factory=list)
    # Numeric stats (only for numeric columns)
    mean: Optional[float] = None
    std: Optional[float] = None
    min_val: Optional[float] = None
    max_val: Optional[float] = None


@dataclass
class DataWiki:
    """Complete data dictionary for a dataset."""
    dataset_name: str = "Untitled Dataset"
    summary: str = ""
    row_count: int = 0
    col_count: int = 0
    columns: list = field(default_factory=list)
    generated_at: str = ""

    def to_markdown(self) -> str:
        """Convert the data wiki to a formatted Markdown string."""
        lines = []

        # Header
        lines.append(f"# 📊 Data Dictionary: {self.dataset_name}")
        lines.append("")
        lines.append(f"> Generated on {self.generated_at}")
        lines.append("")

        # Summary
        if self.summary:
            lines.append("## Summary")
            lines.append("")
            lines.append(self.summary)
            lines.append("")

        # Overview stats
        lines.append("## Overview")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| **Rows** | {self.row_count:,} |")
        lines.append(f"| **Columns** | {self.col_count} |")
        lines.append("")

        # Column details table
        lines.append("## Column Details")
        lines.append("")
        lines.append("| # | Column | Type | Nulls (%) | Unique | Description |")
        lines.append("|---|--------|------|-----------|--------|-------------|")

        for i, col in enumerate(self.columns, 1):
            null_pct = f"{col.null_rate:.1%}" if col.null_rate > 0 else "0%"
            desc = col.description or "_No description_"
            lines.append(
                f"| {i} | `{col.name}` | {col.dtype} | {null_pct} | {col.unique_count:,} | {desc} |"
            )

        lines.append("")

        # Numeric column statistics
        numeric_cols = [c for c in self.columns if c.mean is not None]
        if numeric_cols:
            lines.append("## Numeric Column Statistics")
            lines.append("")
            lines.append("| Column | Mean | Std Dev | Min | Max |")
            lines.append("|--------|------|---------|-----|-----|")
            for col in numeric_cols:
                lines.append(
                    f"| `{col.name}` | {col.mean:,.2f} | {col.std:,.2f} | {col.min_val:,.2f} | {col.max_val:,.2f} |"
                )
            lines.append("")

        # Sample values
        lines.append("## Sample Values")
        lines.append("")
        for col in self.columns:
            if col.sample_values:
                samples = ", ".join([f"`{s}`" for s in col.sample_values[:5]])
                lines.append(f"- **{col.name}**: {samples}")
        lines.append("")

        # Footer
        lines.append("---")
        lines.append("*Generated by AI-DataForge Wiki Generator*")

        return "\n".join(lines)


class WikiGenerator:
    """
    Generates professional Markdown data dictionaries for datasets.

    Uses pandas for statistics and optionally Groq LLM for column descriptions.

    Example:
        generator = WikiGenerator(api_key=os.getenv("GROQ_API_KEY"))
        wiki = generator.generate(df, dataset_name="Insurance Claims")
        print(wiki.to_markdown())
    """

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "llama-3.3-70b-versatile",
        use_llm: bool = True,
    ):
        """
        Initialize the Wiki Generator.

        Args:
            api_key: Groq API key. Falls back to GROQ_API_KEY env var.
            model: LLM model for description generation.
            use_llm: If False, skip LLM-generated descriptions (offline mode).
        """
        self.use_llm = use_llm
        self.model = model

        if self.use_llm:
            self.api_key = api_key or os.getenv("GROQ_API_KEY", "")
            if self.api_key:
                self.llm = ChatGroq(
                    api_key=self.api_key,
                    model=self.model,
                    temperature=0.2,
                    max_tokens=2048,
                )
            else:
                self.use_llm = False

    def generate(
        self,
        df: pd.DataFrame,
        dataset_name: str = "Untitled Dataset",
    ) -> DataWiki:
        """
        Generate a complete data wiki for a DataFrame.

        Args:
            df: The pandas DataFrame to document.
            dataset_name: Human-readable name for the dataset.

        Returns:
            DataWiki object with all column profiles and statistics.
        """
        wiki = DataWiki(
            dataset_name=dataset_name,
            row_count=len(df),
            col_count=len(df.columns),
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )

        # Profile each column
        column_profiles = []
        for col_name in df.columns:
            profile = self._profile_column(df, col_name)
            column_profiles.append(profile)

        # Generate LLM descriptions if available
        if self.use_llm:
            descriptions = self._generate_descriptions(df, dataset_name, column_profiles)
            for profile in column_profiles:
                if profile.name in descriptions:
                    profile.description = descriptions[profile.name]

            # Generate dataset summary
            wiki.summary = self._generate_summary(df, dataset_name)

        wiki.columns = column_profiles
        return wiki

    def _profile_column(self, df: pd.DataFrame, col_name: str) -> ColumnProfile:
        """Generate statistics for a single column."""
        series = df[col_name]

        profile = ColumnProfile(
            name=col_name,
            dtype=str(series.dtype),
            null_count=int(series.isna().sum()),
            null_rate=float(series.isna().mean()),
            unique_count=int(series.nunique()),
            sample_values=[str(v) for v in series.dropna().unique()[:5]],
        )

        # Add numeric stats
        if pd.api.types.is_numeric_dtype(series):
            profile.mean = float(series.mean()) if not series.isna().all() else None
            profile.std = float(series.std()) if not series.isna().all() else None
            profile.min_val = float(series.min()) if not series.isna().all() else None
            profile.max_val = float(series.max()) if not series.isna().all() else None

        return profile

    def _generate_descriptions(
        self,
        df: pd.DataFrame,
        dataset_name: str,
        profiles: list[ColumnProfile],
    ) -> dict:
        """Use LLM to generate human-readable column descriptions."""
        try:
            # Build column info string
            col_info_lines = []
            for p in profiles:
                info = f"- {p.name} (type: {p.dtype}, unique: {p.unique_count}, null%: {p.null_rate:.1%})"
                if p.sample_values:
                    info += f" samples: {p.sample_values[:3]}"
                col_info_lines.append(info)

            col_info = "\n".join(col_info_lines)

            prompt = WIKI_COLUMN_PROMPT.format(
                dataset_name=dataset_name,
                column_info=col_info,
            )

            messages = [
                SystemMessage(content=WIKI_SYSTEM_PROMPT),
                HumanMessage(content=prompt),
            ]

            response = self.llm.invoke(messages)
            # Parse JSON response
            raw = response.content.strip()
            # Clean potential markdown fences
            if raw.startswith("```"):
                raw = raw.split("\n", 1)[1] if "\n" in raw else raw[3:]
            if raw.endswith("```"):
                raw = raw[:-3]

            return json.loads(raw.strip())

        except Exception:
            # Fail silently — descriptions are nice-to-have
            return {}

    def _generate_summary(self, df: pd.DataFrame, dataset_name: str) -> str:
        """Use LLM to generate a dataset summary."""
        try:
            prompt = WIKI_SUMMARY_PROMPT.format(
                dataset_name=dataset_name,
                row_count=len(df),
                col_count=len(df.columns),
                columns=list(df.columns),
                dtypes=dict(df.dtypes.astype(str)),
            )

            messages = [
                SystemMessage(content=WIKI_SYSTEM_PROMPT),
                HumanMessage(content=prompt),
            ]

            response = self.llm.invoke(messages)
            return response.content.strip()

        except Exception:
            return f"Dataset '{dataset_name}' contains {len(df):,} rows and {len(df.columns)} columns."
